SHELL:=/bin/bash
TA=$(shell module load pgi; pgaccelinfo|tail -1|awk '{if ($$1 == "PGI") print $$4; else print "-ta=tesla:cc60"}')

all:
	module load pgi; \
	pgcc -o lake lake.c -I./ -acc $(TA),time -fast -Minfo=accel -Minline -Msafeptr -Mnodepchk -lm

clean:
	rm -f *.o *~ *.dat *.png lake.log lake
